group:
  group_id: "202133184"  # id группы
  group_token: "vk1.a.CY3m2UdGtcsD5t_1srJacrLvzxjy1EvOa0d7KQ_zL0gnyax6bYRKAXjIcYPpadBOYhDZ3eADAE42vgJjQGN_ZmTitxBytFlgyIoPyLTVDcIsEmcvs2VbK6sR5tlxnyJEZWatHU_WehPTxNVzim9B6_EwSjfVRCUPRe3B07fGnXZbNd4zF8YFFX8x1FCuDsTW"  # Токен группы
user:
  user_token: ""  # Токен пользователя